Repository sanaehirotaka/logbook-kai, pull requests merged in 2020-08, with the labels that each got.

#222 同じクラスのウィンドウ位置・サイズを複数記憶する #214
  src/main/java/logbook/internal/gui/InternalFXMLLoader.java
  src/main/java/logbook/internal/gui/Main.java
  src/main/java/logbook/internal/gui/MainMenuController.java
  src/main/java/logbook/internal/gui/Tools.java
Labels: bug

#224 プラグインの後方互換
  src/main/java/logbook/internal/gui/Tools.java
Labels: bug

#228 Colorado特殊攻撃、僚艦夜戦突撃に対応 #226
  src/main/java/logbook/bean/BattleTypes.java
  src/main/java/logbook/internal/PhaseState.java
Labels: due to spec, enhancement

#229 第二艦隊の旗艦の大破警告を抑制するオプション #227
  src/main/java/logbook/api/ApiReqMapNext.java
  src/main/java/logbook/api/ApiReqMapStart.java
  src/main/java/logbook/bean/AppConfig.java
  src/main/java/logbook/bean/DeckPort.java
  src/main/java/logbook/internal/gui/ConfigController.java
  src/main/resources/logbook/gui/config.fxml
Labels: enhancement
